### ISSUE TITLE
Screen is mirrored

### ISSUE THREAD

**Issue by janoist1** [tuupola/micropython-ili934x#2]
I printed some texts but it is mirrored. Is it possible to fix it somehow? Thanks

**Comment by tuupola** [comment]
It is most likely the value of [MADCTL](https://github.com/tuupola/micropython-ili934x/blob/master/ili934x.py#L120). The current `0x08` is for M5Stack. Other possible values could be found from ILI9341 datasheet. You could try values such as `0x28` or `0x48`.

**Comment by janoist1** [comment]
That's worked! Thanks.
